import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.locator('div:nth-child(3) > a').first().click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('san123@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Happylife123$');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.locator('div:nth-child(3) > a').first().click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('.icon-wrapper').click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('.icon-wrapper').click();
  await page.getByRole('link').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.locator('div:nth-child(3) > a').first().click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@admin.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Happylife123$');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('Shift+Home');
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('H');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Happylife123$');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'SIGN IN' }).click();
  await page.getByRole('button', { name: 'SIGN IN' }).click();
});